name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: qa_user
          POSTGRES_PASSWORD: qa_pass
          POSTGRES_DB: qa_helper
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create tables in PostgreSQL
        run: python app/create_tables.py
        env:
          DATABASE_URL: postgresql://qa_user:qa_pass@localhost:5432/qa_helper

      - name: Test database connection
        run: |
          python -c "
          from sqlalchemy import create_engine
          engine = create_engine('postgresql://qa_user:qa_pass@localhost:5432/qa_helper')
          with engine.connect() as conn:
              print('Подключение к PostgreSQL успешно!')
          "